# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default
  #vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate 
        steps:
          - task: TerraformInstaller@1
            inputs:
                terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'adoconnection-terraform'
                  backendAzureRmResourceGroupName: 'terraformstoragetfstate'
                  backendAzureRmStorageAccountName: 'terraformsttfstate'
                  backendAzureRmContainerName: 'terraformtfstate'
                  backendAzureRmKey: 'tfstatefile'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'adoconnection-terraform'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'adoconnection-terraform'